### ISSUE TITLE
Set up repository of dependencies

### ISSUE THREAD

**Issue by sdwfrost** [asmmhossain/phyG#11]
Could you set up a separate repository of dependencies (e.g. FastTree, MAFFT), as .tar.gz archives?

Ideally, you could have a Python script to download these from Github, and install locally within the phlow directory structure, so as not to conflict with any global installs.

**Comment by asmmhossain** [comment]
I have started setting up the repository of dependencies. The installers of different software (archived) are placed in a directory named "dependencies" in the home directory of "phlow".

**Comment by asmmhossain** [comment]
The repository for the dependencies is up to date now. The directory will be kept updated along with the addition of functionalities to the workflow.
