### ISSUE TITLE
Add ORF finders

### ISSUE THREAD

**Issue by sdwfrost** [asmmhossain/phyG#13]
It's useful to have ORF finders, especially for viruses like dengue and HCV which are encoded by a single polyprotein. Could you add the following wrappers:

From the Galaxy toolshed:
[get_orfs_or_cdss](http://toolshed.g2.bx.psu.edu/view/peterjc/get_orfs_or_cdss)

Also, [getorf](http://emboss.sourceforge.net/apps/cvs/emboss/apps/getorf.html), part of the EMBOSS tools. It may be generally useful to enable ALL the EMBOSS tools.

**Comment by asmmhossain** [comment]
The wrappers for "get_orfs_or_cdss" and for EMBOSS tools are now added to the workflow. I have checked "getorf" of the EMBOSS package and it is working fine.
