### ISSUE TITLE
Add ambiguity-aware translation

### ISSUE THREAD

**Issue by sdwfrost** [asmmhossain/phyG#15]
There should also be an option to translate nucleotide sequences into amino acid sequences using a user-selected codon table, and to have the ability to resolve ambiguous nucleotides to amino acids, if there is no ambiguity in the predicted amino acid sequence, or to use a user-defined symbol (e.g. X) if an ambiguous nucleotide does lead to an ambiguous amino acid.

**Comment by asmmhossain** [comment]
I have added DNA2AA which translates nucleotide sequences into amino acid sequences.
