### ISSUE TITLE
Add wrappers for newickutils

### ISSUE THREAD

**Issue by sdwfrost** [asmmhossain/phyG#8]
Could you add a wrapper for newickutils:

http://cegg.unige.ch/newick_utils

This could come under a heading 'Phylogeny processing'

The SVG output could also be used as the basis for displaying a phylogeny in Galaxy.

**Comment by asmmhossain** [comment]
A wrapper for Newick Utilities is added to phlow. The following operations are implemented: display tree in svg format, rooting tree using outgroup/ingroup, derooting a tree and extracting a subtree.
